backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "articles"
    label: "المقالات"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "المحتوى", name: "body", widget: "markdown"}
